config/routes.rb
Rails.application.routes.draw do
  get 'folder/index'
  get 'folder/selectfolder'
  post 'folder/loadphotos'
  resources :folder, only: [:show, :destroy]
  resources :photo,  only: [:show, :edit, :destroy]
  resources :talent
  resources :portfolio
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "folder#index"
end

app/models/talent.rb
class Talent < ApplicationRecord
  has_many :photos
  has_one  :cover, class_name: "Photo"
end

# -----------------------------
#      t.string :talent_code
#      t.string :talent_nbr
#      t.string :talent_name
#      t.string :first_name
#      t.string :last_name
#      t.date :talent_dob
#      t.date :talent_release
# -----------------------------

app/controllers/talent_controller.rb
# ----------------------------------------------------------
# Gallery: A Photographer's gallery/portfolio tool
# Copyright (c) 2024 David S Anderson, All Rights Reserved
# ----------------------------------------------------------

class TalentController < ApplicationController
  before_action :set_talent, only: %i[ show edit update destroy ]

  # GET /talent or /talent.json
  def index
    @talents = Talent.all
  end

  # GET /talent/1 or /talent/1.json
  def show
  end

  # GET /talent/new
  def new
    @talent = Talent.new
  end

  # GET /talent/1/edit
  def edit
  end

  # POST /talent or /talent.json
  def create
    @talent = Talent.new(talent_params)

    respond_to do |format|
      if @talent.save
        format.html { redirect_to talent_url(@talent), notice: "Talent was successfully created." }
        format.json { render :show, status: :created, location: @talent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /talent/1 or /talent/1.json
  def update
    respond_to do |format|
      if @talent.update(talent_params)
        format.html { redirect_to talent_url(@talent), notice: "Talent was successfully updated." }
        format.json { render :show, status: :ok, location: @talent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @talent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talent/1 or /talent/1.json
  def destroy
    @talent.destroy

    respond_to do |format|
      format.html { redirect_to talent_url, notice: "Talent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talent
      @talent = Talent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def talent_params
      params.require(:talent).permit(
        :talent_code, :talent_name, :talent_nbr, 
        :first_name, :last_name, 
        :talent_dob, :talent_release 
      )
    end
end

app/helpers/talent_helper.rb
module TalentHelper
end

app/views/talent/_form.html.haml
= form_for @talent do |f|
  - if @talent.errors.any?
    #error_explanation
      %h2= "#{pluralize(@talent.errors.count, "error")} prohibited this talent from being saved:"
      %ul
        - @talent.errors.full_messages.each do |message|
          %li= message

  = f.label( :talent_code, 'talent_code*', {:title => "DFP talent code"} ) 
  = f.text_field :talent_code
  %br
  = f.label( :talent_name, 'talent name*', {:title => "talent's professional talenting name"} ) 
  = f.text_field :talent_name
  %br
  = f.label( :first_name, 'First name*', {:title => "first and last names"} ) 
  = f.text_field :first_name
  %br
  = f.label( :last_name, 'Last name', {:title => "Your first and last names"} ) 
  = f.text_field :last_name
  %br
  = f.label( :talent_nbr, 'phone', {:title => "contact phone number"} ) 
  = f.text_field :talent_nbr
  %br
  = f.label( :talent_dob, 'talent_dob', {:title => "talent dob"} ) 
  = f.date_field :talent_dob
  %br
  = f.label( :talent_release, 'talent_release date', {:title => "talent release signed date"} ) 
  = f.date_field( "talent_release", {:id => 'talent_release'} )
  %br
  .actions
    = f.submit "&emsp;Save&emsp;".html_safe
  = f.label( :talent_xxx, "&emsp;".html_safe, {:title => "blank for submit button"} ) 

app/views/talent/edit.html.haml
%h1 Editing talent

= render 'form'
%br
= link_to 'view &raquo;'.html_safe, @talent
\|
= link_to 'talent list &raquo;'.html_safe, talent_index_path

app/views/talent/index.html.haml
%h4 Talent
%hr

%table
  %thead
    %tr

  %tbody
    - @talents.each do |talent|
      %tr
        %td= talent.talent_name
        %td= link_to 'view &raquo;'.html_safe, talent
        %td= link_to 'edit &raquo;'.html_safe, edit_talent_path(talent)
        %td= link_to 'delete &raquo;'.html_safe, talent, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to '+NEW &raquo;'.html_safe, new_talent_path

app/views/talent/new.html.haml
%h1 New talent

= render 'form'
%br
= link_to 'talent list &raquo;'.html_safe, talent_index_path

app/views/talent/show.html.haml
%h4= @talent.talent_name
%i#notice= notice
%i= @talent.talent_code
%p= "#{@talent.first_name} #{@talent.last_name}"
%p= number_to_phone(@talent.talent_nbr)
%p= time_ago_in_words(@talent.talent_dob) + " old"
%p= "model release: " + @talent.talent_release.to_s

%br
= link_to 'edit &raquo;'.html_safe, edit_talent_path(@talent)
\&emsp;
= link_to 'talent list &raquo;'.html_safe, talent_index_path