config/routes.rb
Rails.application.routes.draw do
  get 'folder/index'
  get 'folder/selectfolder'
  post 'folder/loadphotos'
  resources :folder, only: [:show, :destroy]
  resources :photo,  only: [:show, :edit, :destroy]
  resources :talent
  resources :portfolio
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "folder#index"
end

app/models/portfolio.rb
# ----------------------------------------------------------
# Gallery: A Photographer's gallery/portfolio tool
# Copyright (c) 2024 David S Anderson, All Rights Reserved
# ----------------------------------------------------------

class Portfolio < ApplicationRecord
  has_many  :portfolio_items

# ----------------------------------------------------------
#      t.string :name
#      t.string :title
# ----------------------------------------------------------


end

app/controllers/portfolio_controller.rb
# ----------------------------------------------------------
# Gallery: A Photographer's gallery/portfolio tool
# Copyright (c) 2024 David S Anderson, All Rights Reserved
# ----------------------------------------------------------

class PortfolioController < ApplicationController
      before_action :set_portfolio, only: %i[ show edit update destroy ]
 
# ----------------------------------------------------------
# index -- show all portfolios; allow user to select one
# ----------------------------------------------------------

  # GET /portfolio or /portfolio.json
  def index
    @portfolios = Portfolio.all
  end

  # POST /portfolio or /portfolio.json
  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolio_url(@portfolio), notice: "Portfolio was successfully created." }
        format.json { render :show, status: :created, location: @portfolio }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end

  end

      # GET /portfolio/new
  def new
     @portfolio = Portfolio.new
  end
 
  # GET /portfolio/1 or /portfolio/1.json
  def show
  end

  # PATCH/PUT /portfolio/1 or /portfolio/1.json
  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolio_url(@portfolio), notice: "Portfolio was successfully updated." }
        format.json { render :show, status: :ok, location: @portfolio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @portfolio.errors, status: :unprocessable_entity }
      end
    end

  end
  
  # GET /portfolio/1/edit
  def edit
  end
  
  # DELETE /portfolio/1 or /portfolio/1.json
  def destroy
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolio_url, notice: "Portfolio was successfully destroyed." }
      format.json { head :no_content }
    end

  end
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
  private

  def set_portfolio()
    @portfolio = Portfolio.find(params[:id])
    true     # returning true continues controller action
    
  rescue ActiveRecord::RecordNotFound
    puts "SHOW: ERROR NOT FOUND"
      flash[:notice] = "portfolio doesn't exist"
      flash[:show_flash] = true
      # redirect_back
      false
  end

  # Only allow a list of trusted parameters through.
  def portfolio_params
    params.require(:portfolio).permit(
      :portfolio_title, :portfolio_name
    )
  end

# ------------------------------------------------------------------------------


end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/portfolio/_form.html.haml
= form_for @portfolio do |f|
  - if @portfolio.errors.any?
    #error_explanation
      %h2= "#{pluralize(@portfolio.errors.count, "error")} prohibited this portfolio from being saved:"
      %ul
        - @portfolio.errors.full_messages.each do |message|
          %li= message

  = f.label( :portfolio_name, 'portfolio name*', {:title => "portfolio name"} ) 
  = f.text_field :portfolio_name
  %br
  = f.label( :portfolio_title, 'portfolio_title*', {:title => "portfolio title"} ) 
  = f.text_field :portfolio_title
  %br
  .actions
    = f.submit "&emsp;Save&emsp;".html_safe
  = f.label( :portfolio_xxx, "&emsp;".html_safe, {:title => "blank for submit button"} ) 

app/views/portfolio/create.html.haml
%h1 Portfolio#create
%p Find me in app/views/portfolio/create.html.haml

app/views/portfolio/destroy.html.haml
%h1 Portfolio#destroy
%p Find me in app/views/portfolio/destroy.html.haml

app/views/portfolio/edit.html.haml
%h1 Editing portfolio

= render 'form'
%br
= link_to 'view &raquo;'.html_safe, @portfolio
\|
= link_to 'portfolio list &raquo;'.html_safe, portfolio_index_path

app/views/portfolio/index.html.haml
%h1 Portfolio#index
%p Find me in app/views/portfolio/index.html.haml

app/views/portfolio/new.html.haml
%h1 New portfolio

= render 'form'
%br
= link_to 'portfolio list &raquo;'.html_safe, portfolio_index_path

app/views/portfolio/show.html.haml
%h1 Portfolio#show
%p Find me in app/views/portfolio/show.html.haml

app/views/portfolio/update.html.haml
%h1 Portfolio#update
%p Find me in app/views/portfolio/update.html.haml